### ISSUE TITLE
cannot launch 1.20.2

### ISSUE THREAD

**Issue by kittenvr** [3arthqu4ke/HeadlessMc#106]
![image](https://github.com/3arthqu4ke/HeadlessMc/assets/103120356/14695f0e-ee46-4d35-805f-aa1e8f76fd54)
![image](https://github.com/3arthqu4ke/HeadlessMc/assets/103120356/86708a28-a4ec-4295-858d-a15ed7cbbe7b)

**Comment by 3arthqu4ke** [comment]
Did you declare your Java Versions in your config like this:
```
hmc.java.versions=C:/Program Files/Java/jre-<version>/bin/java;C:/Program Files/Java/jdk-<version>/bin/java
```
?

I should write an automatic Java detection.

**Comment by kittenvr** [comment]
> Did you declare your Java Versions in your config like this:
> 
> ```
> hmc.java.versions=C:/Program Files/Java/jre-<version>/bin/java;C:/Program Files/Java/jdk-<version>/bin/java
> ```
> 
> ?
> 
> I should write an automatic Java detection.

this fixed my issue but now it launches terminal and minecraft

**Comment by 3arthqu4ke** [comment]
You probably want [this](https://github.com/3arthqu4ke/HMC-Specifics/releases/tag/v1.20.2-1.8.0) in your mods folder.

**Comment by kittenvr** [comment]
> You probably want [this](https://github.com/3arthqu4ke/HMC-Specifics/releases/tag/v1.20.2-1.8.0) in your mods folder.

is it just in the default minecraft instalation

**Comment by 3arthqu4ke** [comment]
> is it just in the default minecraft instalation
Yes, its in .minecraft/mods

**Comment by kittenvr** [comment]
> > is it just in the default minecraft instalation
> 
> Yes, its in .minecraft/mods

i added it but it still isnt headless
![image](https://github.com/3arthqu4ke/HeadlessMc/assets/103120356/96043ae4-15f4-4325-b83c-a0f4c2249569)

**Comment by 3arthqu4ke** [comment]
You need to launch with the `-lwjgl` option.

**Comment by kittenvr** [comment]
> You need to launch with the `-lwjgl` option.

now it doesnt open it but how do i do anything, i cant type

**Comment by 3arthqu4ke** [comment]
I cant really help you with that. Have u tried typing Help, then enter?

**Comment by kittenvr** [comment]
> I cant really help you with that. Have u tried typing Help, then enter?
> 

Doesn't work

**Comment by 3arthqu4ke** [comment]
I cant really work with that, do you have a video or the log output?

**Comment by kittenvr** [comment]
> I cant really work with that, do you have a video or the log output?

When I'm home

**Comment by kittenvr** [comment]
> I cant really work with that, do you have a video or the log output?

https://streamable.com/v9rt47

**Comment by 3arthqu4ke** [comment]
Uhm, thats odd, have u tried a different kind of shell? Like the old Windows terminal?

**Comment by kittenvr** [comment]
> Uhm, thats odd, have u tried a different kind of shell? Like the old Windows terminal?

no, ill try that right now

**Comment by kittenvr** [comment]
just the same thing but the font looks older

**Comment by 3arthqu4ke** [comment]
In the console can you use stuff like ctrl + c?

**Comment by kittenvr** [comment]
> In the console can you use stuff like ctrl + c?

yes, i can use ctrl c

**Comment by kittenvr** [comment]
@3arthqu4ke it is not completed
