### ISSUE TITLE
Running game in another Directory. 

### ISSUE THREAD

**Issue by OrbTweaks** [3arthqu4ke/headlessmc#119]
I am attempting to run your client outside of .minecraft, this is a feature in the normal Launcher. 
Default location is %appdata%/.minecraft
I am looking it to run it out of a custom directory 
Ex. C:\Users\Drew\Documents\Skyblock

What arguments would I add, or what would I change to do so.

**Comment by 3arthqu4ke** [comment]
Try around
```properties
hmc.mcdir=C:/Users/Drew/Documents/Skyblock
```
and/or
```properties
hmc.gamedir=C:/Users/Drew/Documents/Skyblock
```
Inside your `HeadlessMC/config.properties`. I advice against using backslashes inside that file, or else you have to escape them.
