### ISSUE TITLE
provide a option to remove all uuid-based file in HeadlessMc folder on when program start

### ISSUE THREAD

**Issue by serverchanspe** [3arthqu4ke/HeadlessMc#13]
it generated too much on Headless folder

**Comment by 3arthqu4ke** [comment]
Can you try out this version: https://github.com/3arthqu4ke/HeadlessMc/actions/runs/2592961926 ? It will delete leftover files on startup. Also if you quit the game properly, while HeadlessMc is running, either by clicking the Quit button or using the `-commands`/HMC-Specifics quit command they should get deleted properly as well.
