### ISSUE TITLE
Setting player username

### ISSUE THREAD

**Issue by 3arthqu4ke** [3arthqu4ke/headlessmc#164]
### Discussed in https://github.com/3arthqu4ke/headlessmc/discussions/163

<div type='discussions-op-text'>

<sup>Originally posted by **TheNuclearNexus** July 20, 2024</sup>
Is it currently possible to the player's username when launching in offline mode?

I didn't seen anything directly in the code base that allows for this, so unless I am missing something a CLI arg I assume no?</div>

**Comment by TheNuclearNexus** [comment]
Hey I went ahead and updated the code locally to support setting this from both config and the CLI, I can publish the fork if you want to take a look at it. Might be helpful, not sure if it is how you would've gone about doing it though.

**Comment by 3arthqu4ke** [comment]
> Hey I went ahead and updated the code locally to support setting this from both config and the CLI, I can publish the fork if you want to take a look at it. Might be helpful, not sure if it is how you would've gone about doing it though.

Sure, but I might only be interested in the config properties, as I have some plans for new commands regarding the config system.

**Comment by TheNuclearNexus** [comment]
Here you go: [https://github.com/TheNuclearNexus/headlessmc](https://github.com/TheNuclearNexus/headlessmc)
