### ISSUE TITLE
Consider switching to MinecraftAuth?

### ISSUE THREAD

**Issue by andrew121410** [3arthqu4ke/headlessmc#166]
GeyserMC seems to use https://github.com/RaphiMC/MinecraftAuth now and 2FA works for it?

I'm not sure how Minecraft Authentication works at all. So I have no idea if this would allow 2FA support, it does state something about 2FA here. 

https://github.com/RaphiMC/MinecraftAuth?tab=readme-ov-file#log-in-using-credentials

**Comment by 3arthqu4ke** [comment]
Thanks a lot! I just tested it and it seems to work, even against 2FA.
Will integrate it in the next days, then I can also close #90.
