### ISSUE TITLE
i'm probably stupid and i'm sorry, but how?

### ISSUE THREAD

**Issue by FlameUser706** [3arthqu4ke/headlessmc#206]
I'm trying to run commands from the cli on windows, but literally nothing i type works?? i'm running fabric 1.21, and have hmc-specifics installed, so i'm at a loss

**Comment by 3arthqu4ke** [comment]
Could you send the Minecraft log?

**Comment by FlameUser706** [comment]
ope wait- no i'm an idiot i had somehow put the mod in the wrong folder 😭
