### ISSUE TITLE
Embeddium compatibility?

### ISSUE THREAD

**Issue by ChipWolf** [3arthqu4ke/headlessmc#208]
Embeddium has some GL trickery that seems to not enjoy the headless environment. It's a dependency of Iris which is in turn a dependency of our intended test-suite, so I'm keen to get this working.

I have tried swapping xvfb for the lwjgl option, but no dice. This is a 1.20.1 Fabric instance on Temurin 17 in GitHub Actions.

I'm trying to get past this error on start:

```ruby
java.lang.RuntimeException: Failed to create fence object
	at knot//net.minecraft.class_310.handler$zbm000$embeddium$postRender(class_310.java:11565)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1299)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

It looks as though this [mixin](
https://github.com/FiniteReality/embeddium/blob/f8240c7fb5acddd9f7f0971ae2a757feb7c28fb1/src/main/java/org/embeddedt/embeddium/impl/mixin/core/MinecraftClientMixin.java#L73-L82) from Embeddium is to blame:

```java
    @Inject(method = "runTick", at = @At("RETURN"))
    private void postRender(boolean tick, CallbackInfo ci) {
        var fence = GL32C.glFenceSync(GL32C.GL_SYNC_GPU_COMMANDS_COMPLETE, 0);

        if (fence == 0) {
            throw new RuntimeException("Failed to create fence object");
        }

        this.fences.enqueue(fence);
    }
```

**Comment by 3arthqu4ke** [comment]
Ok I will look into this probably this evening more, but it might be very hard to get Embeddium to work with the patched lwjgl, I can work around the glFenceSync but later on there is some native stuff and I am not sure whats going on.

**However**, it should work with xvfb, I just realized that I made a mistake: if in offline mode I force the user to use the patched lwjgl (cause I dont want to get into trouble with mojang/microsoft by providing the game to users without the game), but I am ignoring that they might  have started the game with xvfb, so if you are not using an account you are always running the game with patched lwjgl, xvfb or not. I will probably add a config property, dont think there is an elegant way to detect if we are running with xvfb.

**Comment by 3arthqu4ke** [comment]
Ok, xvfb should now work with [2.3.1](https://github.com/3arthqu4ke/headlessmc/releases/tag/2.3.1), you need to set the system property hmc.check.xvfb=true in your hmc config or as a system property.

mc-runtime-test does not work yet, legacy fabrics repositories seem to be down, so I cannot release the fix yet.

**Comment by 3arthqu4ke** [comment]
mc-runtime-test xvfb should also work now with mc-runtime-test 2.4.1

**Comment by 3arthqu4ke** [comment]
Getting embeddium to run with patched lwjgl would be impractical, please try it with xvfb again.
