### ISSUE TITLE
Error playing 1.12.2 Vanilla with docker, easy fix

### ISSUE THREAD

**Issue by Edouard127** [3arthqu4ke/HeadlessMc#26]
`ERROR : Couldn't load Narrator library : Unable to load library 'fliteWrapper'`

Fixed by doing

`apt-get update`
`apt-get install flite`

:+1:

**Comment by 3arthqu4ke** [comment]
Hmm, this is just some error which is getting logged but does not crash your game, right? Because then I probably wont add those commands to the Dockerfile, the Docker image will most likely not produce any sound anyways.

**Comment by Edouard127** [comment]
It did not crashed the game, but yep sounds right to me
