### ISSUE TITLE
1.12.2

### ISSUE THREAD

**Issue by YongSheng109** [3arthqu4ke/HeadlessMc#32]
how to get forge 1.12.2 working on it without any issue (i got no gpu)

**Comment by 3arthqu4ke** [comment]
1. `login <your email>`
2. Enter your password
3. `download 1.12.2`
4. `forge 1.12.2` 
5. `versions -refresh`
6. You should see your forge 1.12.2 version, copy the name
7. `launch <name> -lwjgl`

For 1.12.2 I recommend putting the HMC-Specifics in your mod folder. (https://github.com/3arthqu4ke/HMC-Specifics)
