### ISSUE TITLE
Fork of ForgeCLI - Is there any way to chose between client and server installation ?

### ISSUE THREAD

**Issue by patgoull** [3arthqu4ke/HeadlessMc#34]
The issue section of the https://github.com/3arthqu4ke/ForgeCLI fork is not active so I thought I'd take a chance here.

I've been messing around with the original ForgeCLI  and your fork of ForgeCLI. I was wondering if there is any way to also install a server by command line. It seems like it's made to install only the client version of forge. I did not see any argument in the doc that could allow this at the moment.

Thank you !

**Comment by 3arthqu4ke** [comment]
AFAIK the forge installer can already install the server via CLI.
`java -jar forge-x.xx.x-installer.jar --installServer`
https://minecraft.fandom.com/wiki/Tutorials/Setting_up_a_Minecraft_Forge_server

**Comment by patgoull** [comment]
How did I miss that. I actually searched something like this.

Thanks a lot !
