### ISSUE TITLE
Future Support

### ISSUE THREAD

**Issue by RemainingToast** [3arthqu4ke/HeadlessMc#40]
It would be cool if you add support for future as it can run headless, see https://github.com/RemainingToast/HeadlessFuture

**Comment by 3arthqu4ke** [comment]
HeadlessMc should be compatible with future? You are talking about HeadlessForge, right?
HeadlessForge is archived and I do not plan on updating it. People can just use your fork.

**Comment by RemainingToast** [comment]
Im talking about adding support for future to headless mc, only provided my repo as an example if case you were curious.

> HeadlessMc should be compatible with future?

yes

**Comment by 3arthqu4ke** [comment]
I don't need or want Future support in HeadlessMc. Futures Installer should modify or create the proper version.json, you can just copy that over and maybe the required jar.
