### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by BeeeeeGIT** [3arthqu4ke/HeadlessMc#42]
Hey I'm new to github so sorry if this is bad and stuff.

I'm trying to run this on a linux server and I'm stuck at the hmc.java.versions key part. I tried downloading a jre from java but I'm not sure what to enter after hmc.java.versions=. Would you know where to download the jre and how I would enter it into the file?

**Comment by 3arthqu4ke** [comment]
You want to give HeadlessMc the path to a java executable. The file that handles any `java ...` command that you put into your terminal. These are typically located inside a bin folder in your java installation.

Using this guide to install jdk 8: https://docs.datastax.com/en/jdk-install/doc/jdk-install/installOpenJdkDeb.html
My java versions land in `/usr/lib/jvm/`. My config looks like this:
```properties
hmc.java.versions=/usr/lib/jvm/jdk1.8.0_openjdk-amd64/bin/java
```
If I have multiple java versions I enter them like this, separated by semicolons:
```properties
hmc.java.versions=/usr/lib/jvm/jdk1.8.0_openjdk-amd64/bin/java;/usr/lib/jvm/jdk17-openjdk-amd64/bin/java
```

**Comment by BeeeeeGIT** [comment]
got it working. thanks so much for the help!
