### ISSUE TITLE
HMC input hangs while game is running

### ISSUE THREAD

**Issue by Robitobi01** [3arthqu4ke/HeadlessMc#5]
Hi, not sure if this belongs here or in the hmc-specifics repo. I think its due to the general console input so I'm opening it here. 
When trying to use HMC with a 1.12.2 14.23.5.2859 Forge client and added hmc-specifics 1.12.2-b1 the console doesn't accept any further commands after using the first one (rarely a couple). The log output and game still work but the input is broken or hangs. When closing the game, hmc realizes the typed commands and then executes them. They obviously run into a "Non existent command" error then because the game is closed at that point.

**Comment by 3arthqu4ke** [comment]
I will test this. You are not using the `-runtime` flag, right? Because when using the HMC-Specifics you don't need to. There is a 1.12.2-b2 btw: https://github.com/3arthqu4ke/HMC-Specifics/releases/tag/1.0.3
Which commands have you tried?

**Comment by 3arthqu4ke** [comment]
I wasn't able to recreate this using headlessmc-launcher-1.0.4-alpha + HMC-Specifics 1.12.2-b2 and your forge version. Both with the lwjgl flag and without I was able to create a SinglePlayer world and Join it. Which OS are you on? Do you use other mods besides the HMC-Specifics? Are you running HeadlessMc from an IDE?

**Comment by Robitobi01** [comment]
I'm running on Linux (5.11.4) and launched without any additional flags. I already tried removing all additional mods before opening the issue. However I've now figured out the issue wasn't caused by an actual "mod" but running Forge+LiteLoader in parallel for 1.12.2. I didn't consider that could be the issue and had it left as the only thing in the mods folder. I'm not exactly sure why this is an issue, I've skimmed through LL source (http://develop.liteloader.com/liteloader/LiteLoader/tree/master) and couldn't find any Mixin or similar modifying GuiScreen. Which is where the specifics hook in? https://github.com/3arthqu4ke/HMC-Specifics/blob/f564e37ad1ef5061a884d0b0a1e63e1ee06a978c/src/main/java/me/earth/headlessmc/mc/mixins/MixinGuiScreen.java#L39
It does actually throw an error I didn't see previously:
```
[java.lang.ThreadGroup:uncaughtException:1052]: java.io.IOError: java.io.IOException: Bad file descriptor
[java.lang.ThreadGroup:uncaughtException:1052]:    at java.io.Console.readLine(Console.java:254)
[java.lang.ThreadGroup:uncaughtException:1052]:    at java.io.Console.readLine(Console.java:272)
[java.lang.ThreadGroup:uncaughtException:1052]: 	at me.earth.headlessmc.command.line.Listener.lambda$listenAsync$1(Listener.java:23)
```
The command still runs and then it stops accepting input until the MC process stops.
Maybe you can try if you can replicate the behavior by dropping the LL jar https://jenkins.liteloader.com/view/1.12.2/job/LiteLoader%201.12.2/lastSuccessfulBuild/artifact/build/libs/liteloader-1.12.2-SNAPSHOT.jar in your mods folder.

The issue can be solved regardless. Thanks anyway!
