### ISSUE TITLE
Suggestions/stupid questions

### ISSUE THREAD

**Issue by HAV0X1014** [3arthqu4ke/HeadlessMc#6]
So I've been using this on a few Google Cloud VPSes, my Raspberry Pi, and also VMs to see how well it performs. On 1.12.2 with the -lwjgl and -paulscode flags it runs like a dream. Even on 2 core 2.2 GHz machines with 2GB of RAM it performs excellent. While using the off-the-shelf release JAR I have found some things to suggest that could make the experience better.

Launch flags could be added on by default through config.properties.
config.properties should have most if not all configurable options placed into it but commented out to show what is configurable.
When using the -lwjgl flag, the folders it creates should be removed/replaced upon game closure. (not sure what they do, appears like garbage left behind, but I am most likely wrong)
Account credential storage should be documented more clearly, so the user doesn't fail to put the login in upon each launch.

(this may be too far of a suggestion-) The -lwjgl and -paulscode flags should be on by default. Most users looking for a truly headless Minecraft launcher may be confused as to why their game crashes due to display issues despite being on a headless launcher.

This project is amazing, keep up the good work ;)

**Comment by 3arthqu4ke** [comment]
Thanks! I currently don't really have the time to work on this but some of these suggestions are very good. 

I will definitely look into why the files from the -lwjgl flag are not getting deleted, that shouldn't happen.

**Comment by 3arthqu4ke** [comment]
<details>
  <summary>Click me for documentation about Account credential storage</summary>
  Put this inside your config:

```properties
hmc.email=<your email>
hmc.password=<your password>
```

</details>
I don't really want to document it because this involves storing your password in clear text. I really want to find a better solution, e.g. using the auth token.

**Comment by 3arthqu4ke** [comment]
Regarding credentials: since [1.4.0](https://github.com/3arthqu4ke/HeadlessMc/releases/tag/1.4.0) just set `hmc.store.accounts=true`, log in and you are done, no more storing passwords in clear text.

Lwjgl and paulscode flags can now be inverted via `hmc.invert.headless.flag=true` and `hmc.invert.pauls.flag=true`.

> Launch flags could be added on by default through config.properties.

Might make macros in the future but for now use the invert properties to invert some of the flags.

Garbage files should get deleted on start up, now.
