### ISSUE TITLE
Command input being erased (on server)

### ISSUE THREAD

**Issue by offeex** [3arthqu4ke/headlessmc#72]
When being on server, all of the chat messages visually erases your commands input, but command still work after pressing enter. 

Reproduce:
- Put this in your config.properties: `hmc.gameargs=--server crystalpvp.cc --port 25565`
- Put any `HMC-specifics` file in your as your fabric/forge mod.
- Try to write commands in chat

**Comment by 3arthqu4ke** [comment]
Moved into #109 for now
