### ISSUE TITLE
[Suggestion] Offline auth support?

### ISSUE THREAD

**Issue by bivashy** [3arthqu4ke/HeadlessMc#77]
Are there any way to use cracked accounts? 
Where we just enter username, and it`ll login as cracked minecraft user

**Comment by 3arthqu4ke** [comment]
As much as I would like to , I just do not want to do anything that could lead to Mojang/Microsoft nuking this.

Though I could probably move the Auth in a way that it only requires an account to download the game files. Launching should not be the issue.
